name: r-reticulate
channels:
  - default
dependencies:
  - python=3.8
  - pip
  - numpy=1.23.3
  - scipy=1.9.3
  - matplotlib=3.6.2
  - jupyterlab=3.6.8
  - pip:
    - scikit-learn==1.2.0
    - scikit-image==0.19.3
    - statsmodels==0.13.5
  